### ISSUE TITLE
Add a prototype removeTab function to PreferenceRegistry

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-preferences#8]
Our app takes advantage of the hawtio preference framework by adding our own tabs. However, by default the hawtio framework adds both 'Console Logging' and 'Reset' tabs, which are not relevant to our app. Currently, I have used the following workaround in our plugin module run function:
```
if (preferencesRegistry.tabs) {
    delete preferencesRegistry.tabs['Console Logging'];
    delete preferencesRegistry.tabs.Reset;
 }
```

This works but feels like a hack. Can an option be added to the preference registry not to add these tabs to start with, preferably, or a prototype removeTab function be added to remove named tabs?

**Comment by gashcrumb** [comment]
Yeah, seems reasonable to me, another option BTW instead of deleting the tabs is to reset it's 'isValid()' attribute to just return false, then the tab is just hidden.

I guess though if this is only used to hide those two tabs, maybe we should just make 'em optional in some way?

**Comment by abkieling** [comment]
@phantomjinx, do you still need this change?

**Comment by phantomjinx** [comment]
@akieling
Our project is no longer using hawtio so its not required for us anymore. Whether its still a worhwhile RFC is up to you.
Thx.
