### ISSUE TITLE
Assess the impact of removing task dependency from 'clean-defs' to 'path-adjust'

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-preferences#9]
I found that `gulp watch` rebuild loops infinitely due to commit 01583c1066d4f0d5a4f7bbc494bc5bcc6c4ab1ae, so I reverted part of it at b1360825f25d4d31b77a294dfe6f7a6d86663a3c. However, I don't fully understand yet what this change may cause.

@gashcrumb Do you think we should recover this task dependency?  We should perhaps create two versions of `clean-defs`, the versions with and without dependency to `path-adjust`?

**Comment by gashcrumb** [comment]
So first question I guess is, why introduce the task dependency, what problem is that trying to solve?

The main thing is originally the `path_adjust` task massages the `.d.ts` files in the current projects dependencies so that the typescript compile works, as originally I couldn't find a way to have the files generated with the right relative paths.  But having to make those changes then means you can't run it as part of `watch`, as that causes the loop since `watch` also looks at `.d.ts` files, actually by design for those times when you're making changes to dependencies.

I'll totally agree that this is all super-complicated :-)

**Comment by tadayosi** [comment]
@gashcrumb Ah, thanks. That's hyper-complicated!

 So for the first time after `rm -r libs/` I run `gulp build` and sometimes get the error depending on when `path-adjust` is run in an indeterministic manner:
```
$ gulp build
[11:27:25] Using gulpfile ~/projects/github/hawtio2/hawtio-preferences/gulpfile.js
[11:27:25] Starting 'bower'...
[11:27:25] Starting 'path-adjust'...
[11:27:25] Starting 'clean-defs'...
[11:27:25] Finished 'clean-defs' after 41 ms
[11:27:25] Starting 'tsc'...
[11:27:25] Finished 'bower' after 479 ms
/Users/tasato/projects/github/hawtio2/hawtio-preferences/libs/hawtio-utilities/d.ts/baseHelpers.d.ts(160,39): error TS2503: Cannot find namespace 'ng'.
[11:27:26] gulp-notify: [Typescript compilation error] #{ error.message }
/Users/tasato/projects/github/hawtio2/hawtio-preferences/libs/hawtio-utilities/d.ts/baseHelpers.d.ts(179,29): error TS2503: Cannot find namespace 'ng'.
[11:27:26] gulp-notify: [Typescript compilation error] #{ error.message }
...
```

Let me consider how it can be resolved.

**Comment by tadayosi** [comment]
@gashcrumb BTW, I don't see the same issue in any other hawtio projects, which don't have a dependency to `path-adjust` and have been fine. Do you have any ideas why?

**Comment by gashcrumb** [comment]
I wonder if `_tsc` needs to run `clean-defs` first like that, as that would cause `path-adjust` to run if it was added as a dependency.  Actually as I think about it, there shouldn't need to be a dependency for `clean-defs`, that's just to delete the current component's `defs.d.ts`, whereas `path-adjust` is only to operate on dependencies under `lib`.

**Comment by tadayosi** [comment]
Hmm, but anyway doesn't `tsc` need a dep to `path-adjust`, whether or not it's dependent on `clean-defs`?  I just thought that your original fix added `path-adjust` to `clean-defs` just because it was a convenient way to make sure `path-adjust` fired before `tsc`, wasn't it?

The key to my solution 35b955e is that the `_xxx` tasks are intended for internal usages, which are all `path-adjust` free, and `watch` relies only on these tasks. This way `watch` rebuilds avoid infinite loops. And the corresponding `xxx` tasks (e.g. `tsc`) are developer facing ones, intended for public usages. These in turn rely on `path-adjust` so can run independently, which are defined like these:

    gulp.task('tsc', ['path-adjust'], function() { gulp.start('_tsc'); });
    ...
    gulp.task('template', ['tsc'], function() { gulp.start('_template'); });

The only scenario it may not work with this solution is when you externally push other libs on the fly like this:

    $ gulp watch --out=../hawtio-preferences/libs/hawtio-utilities/dist/

**Comment by gashcrumb** [comment]
Yeah, definitely `path-adjust` needs to be run before `tsc`and it needs to be run *once* before `watch`, but `tsc` doesn't need `clean-defs`.  Using the `_` tasks like that makes sense for sure, though it certainly does complicate things.

The tricky bit maybe is you just want `path-adjust` to run once, and then not touch the files again, *unless* you've updated them via `bower` or something.

**Comment by tadayosi** [comment]
I agree that my current solution makes things complicated, and it could possibly be overkill. Please feel free to revert my commit and fix it another way when you think of a better/simpler approach.

For now, I'm closing this ticket.
